name: 'Nebula Cherry Pick Robot'
author: rivery.wang
description: 'Create pr to target branch when this pr has special label'
inputs:
  repo_token:
    description: 'repository token to access the codebase'
    required: true
  # pr_label:
  #   description: 'which label to auto create pr'
  #   default: '^v[0-9]*\.[0-9]*(.[0-9])?-cherry-pick$'
  #   required: true
  auto_merge:
    description: 'Should auto merge when creating the new pr?'
    required: true
  from_branch:
    description: 'Which branch to get source commit?'
    required: true
  submodule_path:
    description: 'Does repo contain submodule '
    required: false
  pr_num:
    description: 'Specificy pr num to cherry pick current pr'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'refresh-cw'
  color: 'yellow'